### ISSUE TITLE
opengl

### ISSUE THREAD

**Issue by ssfc** [ssfc/Note#41]
[OpenGL.zip](https://github.com/sortsimilar/Note/files/2996767/OpenGL.zip)

**Comment by sortsimilar** [comment]
1.Figure out GPU model, Intel(R) HD Graphics; (2018-1-20)
2.Install visual studio 2017, done; create microsoft account, done; (2018-1-21)
3.Try a hello world in C++ in IDE, solve problem of flash, done; (2018-1-21)
4.Install CMake in windows, done; CMake is like gcc, done; install CMake in Ubuntu, done; (2018-1-21)
5.Download and unzip source code, done; build sample, Click on Configure until all red lines disappear; generate, done; build all is build solution, done; Choose as startup project, done; (2018-1-21)
6.It mentions CMake, done; (2018-1-21)
7.Change size of window, done; 1024 is size, done; OpenGL Type, done; (2018-1-21)
8.“vec3” is a vector of 3 components in GLSL; change triangle’s color, done; Create and compile our GLSL program from the shaders, done; (2018-1-21)
9.In 3D graphics we will mostly use 4x4 matrices; the reason why we want this order is 4*1; matrix * vertex; perspective projection, done; mvp is model view projection, done; (2018-1-23)
10.Change background color, done; OpenGL only knows about triangles, done; Buffer Objects are OpenGL Objects that store an array of unformatted memory allocated by the OpenGL context (AKA the GPU), done; (2018-1-22)
11.----------------------------------------------------------------------------------------------------------------------
12.Specifies the index of the generic vertex attribute to be modified; Specifies the number of components per generic vertex attribute; Specifies the data type of each component in the array; normalized (GL_TRUE) or converted directly as fixed-point values; byte offset between consecutive generic vertex attributes; a offset of the first component of the first generic vertex attribute; (2018-1-22)
13.glVertexAttribPointer is same in two tutorials; glEnableVertexAttribArray(0) is same; GLFW stands for Graphics Library Framework; This function sets hints for the next call to glfwCreateWindow; done; (2018-1-22)
14.GLFW_SAMPLES specifies the desired number of samples to use for multisampling; GLFW_CONTEXT_VERSION_MAJOR and GLFW_CONTEXT_VERSION_MINOR specify the client API version that the created context must be compatible with; (2018-1-22)
15.OpenGL for Embedded Systems (OpenGL ES or GLES) is a subset, done; GLFW_CONTEXT_VERSION_MAJOR and GLFW_CONTEXT_VERSION_MINOR specify the client API version that the created context must be compatible with; GLFW_OPENGL_FORWARD_COMPAT is GLFW_TRUE if the window's context is an OpenGL forward-compatible one; GLFW_OPENGL_PROFILE specifies which OpenGL profile to create the context for; (2018-1-22)
16.Red book and blue book both are OpenGL tutorials; openCV is graphic to data, openGL is data to graphic, done; .图形学是为了在电脑里模拟物体而形成的一门研究领域;  (2018-1-22)
17.Specifies an array in which the generated buffer object names are stored; Specifies the target to which the buffer object is bound. The symbolic constant must be                     GL_ARRAY_BUFFER or GL_ELEMENT_ARRAY_BUFFER; glGenVertexArrays returns n vertex array object names in arrays; glBindVertexArray binds the vertex array object with name array; (2018-1-22)
18.Still, I cannot relate graphic courses with openGL’s tutorial, now I can; (2018-1-22)                
19.glClear — clear buffers to preset values; GL_COLOR_BUFFER_BIT, Indicates the buffers currently enabled for color writing; GL_DEPTH_BUFFER_BIT, Indicates the depth buffer; GL_ACCUM_BUFFER_BIT; GL_STENCIL_BUFFER_BIT; (2018-1-22)
20.glBufferData, glNamedBufferData — creates and initializes a buffer object's data store; The solution to this problem is to store the depth (i.e. “Z”) component of each fragment in a buffer; One or more executables are created in a program object by successfully attaching shader objects to it with glAttachShader, successfully compiling the shader objects with glCompileShader, and successfully linking the program object with glLinkProgram; done; (2018-1-22)
21.Uniform variables are used to communicate with your vertex or fragment shader from "outside"; Values that stay constant for the whole mesh; Uniform variables are read-only and have the same value among all processed vertices; glGetUniformLocation — return the location of a uniform variable; Points to a null terminated string containing the name of the uniform variable whose location is to be queried; glGetUniformLocation  returns an integer that represents the location of a specific uniform	variable within a program object; (2018-1-22)
22.This function sets an input mode option for the specified window. The mode must be one of GLFW_CURSOR, GLFW_STICKY_KEYS or GLFW_STICKY_MOUSE_BUTTONS;  GLFW_CURSOR; GLFW_CURSOR_NORMAL; GLFW_CURSOR_HIDDEN; GLFW_CURSOR_DISABLED; GLFW_STICKY_KEYS; GLFW_TRUE to enable sticky keys, or GLFW_FALSE to disable it; This is useful when you are only interested in whether mouse buttons have been pressed but not when or in which order; (2018-1-22)
23.-----------------------------------------------------------------------------------------------------------------------
24.Specify the red, green, blue, and alpha values used when the color buffers are cleared; Values specified by glClearColor are clamped to the range [0, 1]; glEnable — enable or disable server-side GL capabilities; If enabled, do alpha testing; If enabled,                       do depth comparisons and update the depth buffer; glDepthFunc specifies the function used to compare each incoming pixel depth value with the depth value present in the depth buffer; Never passes; Passes if the incoming depth value is less than the stored depth value; Passes if the incoming depth value is equal to the stored depth value; Passes if the incoming depth value is less than or equal to the stored depth value; (2018-1-23)
25.The Model, View and Projection matrices are a handy tool to separate transformations cleanly; the reason why there is translation*rotation*scale is because player moves it; 
26.Add size to measure, done; (2018-1-24)                
27.You also need to clear the depth each frame, instead of only the color; (2018-1-27)                
28.Find path of cpp file, C:\Users\take_\Dropbox\program\C++\openGL\ogl-master\tutorial01_first_window, done; (2018-1-27)
29.int glfwInit 	( 	void  		);  This function initializes the GLFW library. Before most GLFW functions can be used, GLFW must be initialized, and before an application terminates GLFW should be terminated in order to free any resources allocated during or after initialization; (2018-1-27)	
30.glfwCreateWindow (int width, int height, const char *title, GLFWmonitor *monitor, GLFWwindow *share) 	Creates a window and its associated context; (2018-1-27)
31. In a short conclusion, CMake help you to manage and build your source codes effectively. If you have some troubles with gcc and Makefile, just move out to CMake; (2018-1-27)
32.Makefile到底是什么呢？说的白话点就是程序写完要编译，在linux下用gcc编译，当文件有很多，通过写个makefile，类似脚本，可以自动编译，就不需要手动一个个编译; (2018-1-27)
33.cmake_minimum_required; If the current version of CMake is lower than that required it will stop processing the project and report an error. When a version higher than 2.4 is specified the command implicitly invokes; (2018-1-27)
34.project, Set a name, version, and enable languages for the entire project; try to change to hello, change sln file name, done; (2018-1-27)
35.-------------------------------------------------------------------------------------------------------------------------
36.add_executable, Adds an executable target called <name> to be built from the source files listed in the command invocation; target_link_libraries, Specify libraries or flags to use when linking a given target. The named <target> must have been created in the current directory by a command such as add_executable() or add_library(); done; (2018-1-27)
37.Remove 2 to 17, done; remove 18, done; remove playground, done; remove 3 misc 05, done; remove 2 to 18 in sample_project, done; remove playground in sample_project, done; remove 3 misc in sample_project, done; (2018-1-27)
38.Change sample_project to tutorial_01, done; try to run tutorial 2, done; change target to target_02, done; change target to target_01, done; we can use open project directly,  (2018-1-28)
39.Let’ set length to 1200, width to 600; (2018-1-28)
40.Try to apply 1200, 600 to tutorial 2 project, done; also show triangle successfully, done; try to change sequence of 3 vertices, result is same; change (0, 1) to (0, 0), done; the coordinate is same; when drawing triangle, coordinate is defined in static const GLfloat g_vertex_buffer_data[]; (2018-1-28)
41.Figure out common color: google search RGB color table, done; (2018-1-28)
42.Try to run single tutorial 3, done; (2018-1-28)
43.OpenGL Mathematics (GLM) is a C++ mathematics library for graphics software based on the OpenGL Shading Language (GLSL) specification; To use GLM, a programmer only has to include <glm/glm.hpp>. This provides all the GLSL features implemented by GLM; (2018-1-28)
44.Changing glm::mat4(1.0f) does not change result; View function set camera location and direction; model matrix convert model coordinate to world coordinate; view matrix convert world coordinate to camera coordinate, done; (2018-1-28) 
45.change radians value, 30 becomes larger, 90 becomes smaller, radians change size of shape; change aspect ratio, its ratio of length / width, done; gl_Position =  MVP * vec4(vertexPosition_modelspace,1); 
46.What is glm::mat4, give up; (2018-1-28)
47.---------------------------------------------------------------------------------------------------------------------
48.Get familiar with header file included; #include <GL/glew.h>; The OpenGL Extension Wrangler Library (GLEW) is a cross-platform open-source C/C++ extension loading library. GLEW provides efficient run-time mechanisms for determining which OpenGL extensions are supported on the target platform; #include <glfw3.h>, This defines all the constants, types and function prototypes of the GLFW API. It also includes the OpenGL header from your development environment and defines all the constants and types necessary for it to work on your platform without including any platform-specific headers; include <glm/glm.hpp>. This provides all the GLSL features implemented by GLM; #include <glm/gtc/matrix_transform.hpp> // glm::translate, glm::rotate, glm::scale, glm::perspective;  (2018-1-28) 
49.Change camera location, done; (2018-1-28)
50.Try to create a new project of OpenGL, learn to use CMake to create a folder containing single project, modify CMakeLists.txt, done; (2018-1-28)
51.glm::mat4(1.0f) is identity matrix; done; (2018-1-28)
52.Try to implement translate, glm::mat4 Model = glm::translate(glm::mat4(1.0f), glm::vec3(1.0f)); figure out glm::translate, move in x axis, done, move in y axis, done, move in z axis, done; (2018-1-28)
53.try scale function, Model = glm::scale(glm::mat4(1.0f), glm::vec3(1, 2, 1)), done; try rotation function, no need to add new library; (2018-1-28)
54.No need to have glm::; remove glm::, done; mat4 is In 3D graphics we will mostly use 4x4 matrices; (2018-1-28)
55.Deal with rotation, give up; void glfwMakeContextCurrent 	( 	GLFWwindow *  	window	) , This function makes the OpenGL or OpenGL ES context of the specified window current on the calling thread. A context can only be made current on a single thread at a time and each thread can have only a single current context at a time. (2018-1-28)
56.Run tutorial 04, done; change size to 600, 600; void glfwTerminate 	( 	void  		),  This function destroys all remaining windows and cursors, restores any modified gamma ramps and frees any other allocated resources. Once this function is called, you must again call glfwInit successfully before you will be able to use most GLFW functions. (2018-1-29)
57.Change camera location to see whether becomes square, yes; let’s change z=-1 to z=-2, done; change y=-1 to y=-2, done; (2018-1-29)
58.Draw two triangles in t3, done; set different coordinate value in t3,  glDrawArrays(GL_TRIANGLES, 0, 2*3), done; (2018-1-29)
59.------------------------------------------------------------------------------------------------------------
60.Generate color in t4, give up; run t5, done; try uvtemplate.bmp instead of uvtemplate.DDS; change camera position, done; (2018-1-30)
61.Texture need a new file texture.cpp, Creating textures is very similar to creating vertex buffers : Create a texture, bind it, fill it, and configure it; the program can load BMP and DDS format; (2018-1-30)
62.Draw our own BMP file, become total black; glGenTextures returns n texture names in textures; glBindTexture — bind a named texture to a texturing target; glTexImage2D — specify a two-dimensional texture image; glTexParameter, glTextureParameter — set texture parameters; (2018-1-30)
63.What is layout location? UV mapping is the 3D modeling process of projecting a 2D image to a 3D model's surface for texture mapping; GLFW2 can do that too (but only for TGA files, and this feature has been removed in GLFW3, that we now use); (2018-1-30)
64.Using the compressed texture is DDS file, In general, you should only use compressed textures, since they are smaller to store, almost instantaneous to load, and faster to use; the main drawback it that you have to convert your images through The Compressonator (or any similar tool), done; (2018-1-30)
65.Since this code will be re-used throughout the tutorials, we will put the code in a separate file : common/controls.cpp, and declare the functions in common/controls.hpp so that tutorial06.cpp knows about them; we finally know we common file is; common contain control.cpp, shader.cpp, texture.cpp; (2018-1-31)
66.It’s a do-while loop, The major modification is that instead of computing the MVP matrix once, we now have to do it every frame. So let’s move this code inside the main loop; computeMatricesFromInputs() reads the keyboard and mouse and computes the Projection and View matrices; getProjectionMatrix() just returns the computed Projection matrix; getViewMatrix() just returns the computed View matrix; View and Projection are set in controls.cpp; (2018-1-31)
67.The Model, View and Projection matrices; run t6, done; fix coordinate that figure is shown in the center; int xpos, ypos; become double in real; change mouse speed, done; If you had a “=” instead, you would be forced back to your original orientation each frame, which isn’t good; test up down left right; (2018-1-31)
68.If you have a fast computer, and you run at 60 fps, you’d move of 60*speed units in 1 second, If you have a fast computer, and you run at 60 fps, you’d move of 1/60 * speed units in 1 frame, so 1*speed in 1 second; Now GLFW 3 requires setting up a callback for this. It's a bit too complicated for this beginner's tutorial, so it's disabled instead; (2018-1-31) 
69.Restrict vertical angle, done; run t7, done; (2018-1-31)
70.What is obj file? OBJ (or .OBJ) is a geometry definition file format first developed by Wavefront Technologies for its Advanced Visualizer animation package. The file format is open and has been adopted by other 3D graphics application vendors; Lines beginning with a hash character (#) are comments. # this is a comment; (2018-1-31)
71.--------------------------------------------------------------------------------------------------------------------------
72.V, # List of geometric vertices, with (x,y,z[,w]) coordinates, w is optional and defaults to 1.0; vt, # List of texture coordinates, in (u, v [,w]) coordinates, these will vary between 0 and 1, w is optional and defaults to 0; t is short for texture; vn, # List of vertex normals in (x,y,z) form; normals might not be unit vectors; n is short for normals; f, # Polygonal face element (see below); (2018-1-31)
73.Blender is a professional, free and open-source 3D computer graphics software toolset used for creating animated films, visual effects, art, 3D printed models, interactive 3D applications and video games; change perpendicular to orthogonal, done; (2018-2-2)
74.Get familiar with blender, download blender, watch tutorial; perhaps we can use blender as an overview of openGL and computer graphic; change function to map, done; (2018-2-5)
